import Foundation
import Darwin

struct SSHLaunchRequest: Codable, Sendable {
    var tabID: UUID
    let token: String
    let connectionID: SSHConnectionID
    let credential: String
    let master: SSHMaster
    let shell: SSHShell
    var integrationScope: SSHIntegrationScope? = nil
    /// App-observed routing identity, used only for sidebar grouping.
    var presentationScope: SSHIntegrationScope? = nil
    var integrationGrant: SSHIntegrationGrant? = nil
    /// Public routing ID; remote IPC credentials are generated by the helper.
    var sessionID: String { String(connectionID.rawValue.uuidString.replacingOccurrences(of: "-", with: "").lowercased().prefix(24)) }
    var origin: AgentProcess? = nil
    var sshProcess: AgentProcess? = nil
    var terminalDevice: UInt32? = nil
}

struct SSHCloseNotice: Codable, Sendable {
    let credential: String
    let status: Int32
    let recoverable: Bool
    var transportExitedNormally: Bool? = nil

    // OpenSSH reserves 255 for transport/setup failures. A remote command can
    // also return 255, so that value still requires the helper's exit receipt.
    var remoteExitStatus: Int32? {
        transportExitedNormally == true && (0..<255).contains(status) ? status : nil
    }
}
struct SSHResumeDecision: Codable, Sendable {
    let credential: String
    var launch: SSHLaunchRequest? = nil
    var exitStatus: Int32? = nil
    var waiting: Bool? = nil
}

struct SSHConsentRequest: Codable, Sendable {
    let id: UUID
    let tabID: UUID
    let token: String
    let scope: SSHIntegrationScope
    let origin: AgentProcess
}

/// A missing grant is an explicit cancellation, distinct from ordinary SSH.
struct SSHConsentResponse: Codable, Sendable {
    let grant: SSHIntegrationGrant?
}

/// Runs as a foreground terminal command. The real ssh child inherits its PTY
/// and process group, so authentication and ordinary terminal input stay native.
enum SSHLauncherCommand {
    nonisolated(unsafe) private static var child: pid_t = 0

    static func run(_ args: [String]) -> Int32 {
        let environment = ProcessInfo.processInfo.environment
        guard let executable = environment["DISPATCH_SSH_EXECUTABLE"] ?? ShellCommandWrapper.ssh.executable(in: environment) else {
            try? FileHandle.standardError.write(contentsOf: Data("ssh is not installed or is missing from PATH.\n".utf8)); return 127
        }
        guard let directory = environment["DISPATCH_HERDR_DIRECTORY"],
              let rawTab = environment["DISPATCH_HERDR_TAB"], let tab = UUID(uuidString: rawTab),
              let token = environment["DISPATCH_HERDR_TOKEN"],
              let invocation = SSHInvocation.parse(args, isTerminal: isatty(STDIN_FILENO) == 1),
              let configuration = resolvedConfiguration(invocation, executable: executable),
              let scope = SSHIntegrationScope(executable: executable, destination: invocation.destination, configuration: configuration),
              let origin = AgentProcess.capture(getpid()) else { return replace(executable, args) }
        guard let grant = permission(scope: scope, directory: directory, tab: tab, token: token, origin: origin) else { return 130 }
        guard grant.isCurrent, grant.profile != .ordinary else { return replace(executable, args) }
        // A configuration edited while the consent sheet was open cannot carry
        // the old account's grant into the new invocation.
        guard let current = resolvedConfiguration(invocation, executable: executable),
              SSHIntegrationScope(executable: executable, destination: invocation.destination, configuration: current) == scope else {
            return replace(executable, args)
        }
        let id = SSHConnectionID(), credential = UUID().uuidString
        let sessionID = String(id.rawValue.uuidString.replacingOccurrences(of: "-", with: "").lowercased().prefix(24))
        let folder = URL(fileURLWithPath: directory).appendingPathComponent("s-" + id.rawValue.uuidString.prefix(12))
        do { try FileManager.default.createDirectory(at: folder, withIntermediateDirectories: false, attributes: [.posixPermissions: 0o700]) }
        catch { return replace(executable, args) }
        var announced = false
        var connectingAnnounced = false
        // Once announced, the app owns this directory until the originating
        // shell and every native consumer have released their connection.
        defer { if !announced { try? FileManager.default.removeItem(at: folder) } }
        let master = SSHMaster(executable: executable, controlPath: folder.appendingPathComponent("master").path, destination: invocation.destination)
        let remote = remoteCommand(sessionID: sessionID, grant: grant, command: invocation.command)
        let arguments = invocation.masterArguments(controlPath: master.controlPath, remoteCommand: remote)
        var pointers = ([executable] + arguments).map { strdup($0) }; pointers.append(nil)
        var env = environment.map { strdup($0.key + "=" + $0.value) }; env.append(nil)
        defer { pointers.forEach { free($0) }; env.forEach { free($0) } }
        var pid: pid_t = 0
        let launched = executable.withCString { executable in
            pointers.withUnsafeMutableBufferPointer { arguments in
                env.withUnsafeMutableBufferPointer { environment in
                    posix_spawn(&pid, executable, nil, nil, arguments.baseAddress!, environment.baseAddress!)
                }
            }
        }
        guard launched == 0 else { return replace(executable, args) }
        child = pid
        let previousHup = signal(SIGHUP) { _ in if SSHLauncherCommand.child > 0 { kill(SSHLauncherCommand.child, SIGHUP) } else { _exit(129) } }
        let previousTerm = signal(SIGTERM) { _ in if SSHLauncherCommand.child > 0 { kill(SSHLauncherCommand.child, SIGTERM) } else { _exit(143) } }
        let previousInt = signal(SIGINT, SIG_IGN)
        defer { child = 0; signal(SIGHUP, previousHup); signal(SIGTERM, previousTerm); signal(SIGINT, previousInt) }
        var status: Int32 = 0
        while true {
            let result = waitpid(pid, &status, WNOHANG)
            if result == pid { break }
            if result < 0 && errno != EINTR { break }
            let ready = FileManager.default.fileExists(atPath: master.controlPath)
            if (!connectingAnnounced || ready) && !announced {
                let request = SSHLaunchRequest(tabID: tab, token: token, connectionID: id, credential: credential,
                    master: master, shell: SSHShell(destination: invocation.destination, options: invocation.options, executable: executable),
                    integrationScope: scope, integrationGrant: grant, origin: origin, sshProcess: AgentProcess.capture(pid), terminalDevice: AgentProcess.info(getpid())?.e_tdev)
                // Publish progress while OpenSSH is still connecting/authenticating.
                // Only the ready request permits the app to open helper channels.
                let file = URL(fileURLWithPath: directory).appendingPathComponent(id.rawValue.uuidString + (ready ? ".sshrequest" : ".sshconnecting"))
                if let data = try? JSONEncoder().encode(request), (try? data.write(to: file, options: .atomic)) != nil {
                    if ready { announced = true }
                    else { connectingAnnounced = true }
                }
            }
            usleep(50_000)
        }
        let result = status & 0x7f == 0 ? (status >> 8) & 0xff : 128 + (status & 0x7f)
        guard announced else { return result }
        child = 0
        return awaitRecovery(directory: directory, id: id, credential: credential, status: result,
                             recoverable: invocation.command == nil, exitedNormally: status & 0x7f == 0)
    }

    /// The launcher remains the terminal's foreground owner while offline.
    /// Resumption arrives through its private mailbox, never terminal input.
    static func awaitRecovery(directory: String, id initialID: SSHConnectionID, credential initialCredential: String,
                              status initialStatus: Int32, recoverable: Bool, exitedNormally initialExitedNormally: Bool,
                              input: Int32 = STDIN_FILENO) -> Int32 {
        var id = initialID, credential = initialCredential, status = initialStatus
        var exitedNormally = initialExitedNormally
        while true {
            let root = URL(fileURLWithPath: directory)
            let notice = SSHCloseNotice(credential: credential, status: status, recoverable: recoverable, transportExitedNormally: exitedNormally)
            let closed = root.appendingPathComponent(id.rawValue.uuidString + ".sshclosed")
            guard let bytes = try? JSONEncoder().encode(notice), (try? bytes.write(to: closed, options: .atomic)) != nil else { return status }
            let reply = root.appendingPathComponent(id.rawValue.uuidString + ".sshresume")
            var modes = termios()
            let hasModes = tcgetattr(input, &modes) == 0
            var offline = false
            var decision: SSHResumeDecision?
            while FileManager.default.fileExists(atPath: directory) {
                if let bytes = try? Data(contentsOf: reply), bytes.count < 262144,
                   let value = try? JSONDecoder().decode(SSHResumeDecision.self, from: bytes), value.credential == credential {
                    try? FileManager.default.removeItem(at: reply)
                    if value.waiting == true {
                        offline = true
                        if hasModes { var raw = modes; cfmakeraw(&raw); tcsetattr(input, TCSANOW, &raw) }
                    } else { decision = value; break }
                }
                // Do not consume type-ahead while the app checks an ordinary
                // shell exit. Only an authenticated recovery decision parks input.
                var descriptor = pollfd(fd: input, events: Int16(POLLHUP | (offline ? POLLIN : 0)), revents: 0)
                if poll(&descriptor, 1, 50) > 0 {
                    if descriptor.revents & Int16(POLLHUP | POLLERR | POLLNVAL) != 0 { break }
                    if offline {
                        var discard = [UInt8](repeating: 0, count: 4096)
                        if read(input, &discard, discard.count) <= 0 { break }
                    }
                }
            }
            if offline { tcflush(input, TCIFLUSH) }
            if hasModes { tcsetattr(input, TCSANOW, &modes) }
            guard let decision else { return status }
            if let exit = decision.exitStatus { return exit }
            guard recoverable, let request = decision.launch, let grant = request.integrationGrant else { return status }
            id = request.connectionID; credential = request.credential
            var arguments = request.master.arguments(command: remoteCommand(sessionID: request.sessionID, grant: grant, command: nil))
            if let index = arguments.firstIndex(of: "-T") { arguments[index] = "-tt" }
            var pointers = ([request.master.executable] + arguments).map { strdup($0) }; pointers.append(nil)
            var environment = ProcessInfo.processInfo.environment.map { strdup($0.key + "=" + $0.value) }; environment.append(nil)
            var pid: pid_t = 0
            let launched = request.master.executable.withCString { executable in
                pointers.withUnsafeMutableBufferPointer { arguments in
                    environment.withUnsafeMutableBufferPointer { posix_spawn(&pid, executable, nil, nil, arguments.baseAddress!, $0.baseAddress!) }
                }
            }
            pointers.forEach { free($0) }; environment.forEach { free($0) }
            guard launched == 0 else { status = 255; exitedNormally = false; continue }
            child = pid
            var waitStatus: Int32 = 0
            while waitpid(pid, &waitStatus, 0) < 0 && errno == EINTR {}
            child = 0
            exitedNormally = waitStatus & 0x7f == 0
            status = exitedNormally ? (waitStatus >> 8) & 0xff : 128 + (waitStatus & 0x7f)
        }
    }

    static func resolvedConfiguration(_ invocation: SSHInvocation, executable: String) -> String? {
        struct Input: Codable { let executable: String; let arguments: [String] }
        let arguments = ["-G", "-o", "ClearAllForwardings=no"] + invocation.options + ["--", invocation.destination] + (invocation.command.map { [$0] } ?? [])
        do {
            let data = try AppReplay.query(kind: "ssh.configuration", input: JSONEncoder().encode(Input(executable: executable, arguments: arguments))) {
                let process = Process(), pipe = Pipe()
                process.executableURL = URL(fileURLWithPath: executable)
                // Native clones suppress duplicate forwarded listeners. Resolve the
                // consent identity with forwarding definitions visible in both launches;
                // the real SSH invocation still keeps ClearAllForwardings=yes. This also
                // preserves saved fingerprints from ordinary first connections.
                process.arguments = arguments
                process.standardInput = FileHandle.nullDevice; process.standardOutput = pipe; process.standardError = FileHandle.nullDevice
                do {
                    try process.run(); pipe.fileHandleForWriting.closeFile()
                    let timeout = DispatchWorkItem { if process.isRunning { process.terminate() } }
                    DispatchQueue.global().asyncAfter(deadline: .now() + 10, execute: timeout)
                    defer { timeout.cancel(); pipe.fileHandleForReading.closeFile() }
                    var data = Data()
                    while let bytes = try pipe.fileHandleForReading.read(upToCount: 65_536), !bytes.isEmpty {
                        guard bytes.count <= 1_048_576 - data.count else {
                            if process.isRunning { process.terminate() }; process.waitUntilExit(); return try JSONEncoder().encode(Optional<String>.none)
                        }
                        data.append(bytes)
                    }
                    process.waitUntilExit()
                    let configuration = String(decoding: data, as: UTF8.self)
                    return try JSONEncoder().encode(process.terminationStatus == 0 && invocation.supports(configuration: configuration) ? configuration : nil)
                } catch { if process.isRunning { process.terminate(); process.waitUntilExit() }; return try JSONEncoder().encode(Optional<String>.none) }
            }
            return try JSONDecoder().decode(String?.self, from: data)
        } catch { AppReplay.fail(error); return nil }
    }

    private static func permission(scope: SSHIntegrationScope, directory: String, tab: UUID, token: String,
                                   origin: AgentProcess) -> SSHIntegrationGrant? {
        let id = UUID(), root = URL(fileURLWithPath: directory)
        let request = root.appendingPathComponent(id.uuidString + ".sshconsent")
        let reply = root.appendingPathComponent(id.uuidString + ".sshchoice")
        defer { try? FileManager.default.removeItem(at: request); try? FileManager.default.removeItem(at: reply) }
        let value = SSHConsentRequest(id: id, tabID: tab, token: token, scope: scope, origin: origin)
        guard let data = try? JSONEncoder().encode(value), (try? data.write(to: request, options: .atomic)) != nil else { return .init(profile: .ordinary) }
        let deadline = ContinuousClock.now.advanced(by: .seconds(120))
        while ContinuousClock.now < deadline {
            if let data = try? Data(contentsOf: reply), data.count < 16_384,
               let response = try? JSONDecoder().decode(SSHConsentResponse.self, from: data) {
                guard let grant = response.grant else { return nil }
                if grant.isCurrent { return grant }
            }
            guard FileManager.default.fileExists(atPath: directory) else { break }
            usleep(50_000)
        }
        // A late click on Cancel must never race an automatic SSH connection.
        return nil
    }

    static func remoteCommand(sessionID: String, grant: SSHIntegrationGrant, command: String?) -> String {
        precondition(SSHBootstrap.validSessionID(sessionID) && grant.profile != .ordinary)
        let capabilities = grant.capabilities == SSHIntegrationGrant.capabilities(grant.profile, hooks: grant.hooks)
            ? "" : " --capabilities " + HerdrLaunch.quote(grant.capabilities.sorted().joined(separator: ","))
        let fallback = command.map { "exec \"${SHELL:-/bin/sh}\" -c " + HerdrLaunch.quote($0) } ?? "exec \"${SHELL:-/bin/sh}\" -l"
        // The ordinary command occurs once, after setup completes or fails.
        // No `|| fallback` follows helper exec: an already-started command's
        // status is final, even when its helper channel subsequently fails.
        let script = """
        prepare() {
          \(SSHBootstrap.privateDirectoryScript)
          enter_private launches && enter_private '\(sessionID)' || exit 1
          attempt=0
          while test ! -e ready && test ! -L ready && test "$attempt" -lt 325; do
            sleep 0.2
            attempt=$((attempt + 1))
          done
          safe_file ready || exit 1
          IFS= read -r helper < ready || exit 1
          rm -f ready
          cd .. && rmdir '\(sessionID)' 2>/dev/null
          case "$helper" in
            .dispatch/bin/*/dsptch)
              digest=${helper#.dispatch/bin/}
              digest=${digest%/dsptch}
              test "${#digest}" = 64 || exit 1
              case "$digest" in *[!0-9a-f]*) exit 1;; esac
              cd .. && enter_private bin && enter_private "$digest" || exit 1
              safe_file dsptch && test -x dsptch || exit 1
              if command -v sha256sum >/dev/null 2>&1; then hash=$(sha256sum dsptch | cut -d ' ' -f 1)
              elif command -v shasum >/dev/null 2>&1; then hash=$(shasum -a 256 dsptch | cut -d ' ' -f 1)
              else exit 1; fi
              test "$hash" = "$digest" || exit 1
              printf '%s\\n' "$helper";;
            *) exit 1;;
          esac
        }
        helper=$(prepare)
        if test "$?" = 0; then
          cd "$HOME" || exit 1
          \(SSHBootstrap.captureExport)exec "$HOME/$helper" login \(grant.profile.rawValue)\(grant.hooks ? " --hooks" : "")\(capabilities) --session '\(sessionID)'\(command.map { " " + HerdrLaunch.quote($0) } ?? "")
        fi
        printf 'Dispatch SSH integration unavailable; opening the remote shell.\\r\\n' >&2
        export TERM=xterm-256color
        \(fallback)
        """
        // Reconnect wraps this in another command shell. Replace that shell
        // explicitly so helper login remains a direct child of sshd.
        return "exec /bin/sh -c " + HerdrLaunch.quote(script)
    }

    private static func replace(_ executable: String, _ arguments: [String]) -> Int32 {
        var pointers = ([executable] + arguments).map { strdup($0) }; pointers.append(nil)
        defer { pointers.forEach { free($0) } }
        pointers.withUnsafeMutableBufferPointer { _ = execv(executable, $0.baseAddress!) }
        return 127
    }
}
