use super::{Done, Id, Io};
use std::rc::Rc;

/// Existing renderer control callbacks; c1654cc StreamHandler.swift:439-466.
/// Only a claiming multiplexer interprets Data. Exit is generated by core.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum Control {
    Start,
    Data(Vec<u8>),
    End,
    Exit(Option<i32>),
}

/// Uses the original terminal's checked keys path; no PTY or process is transferred.
pub type ControlWrite = Rc<dyn Fn(&mut dyn Io, &[u8], Done<()>)>;

/// A normal backend route, also identifying the producer's private stream.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct ControlTarget {
    pub key: String,
    pub id: Id,
}
